services:
  api-server:
    build:
      context: ./apps/api-server
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
      - redis

  web-client:
    build:
      context: ./apps/web-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: debate
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
